### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [WirelessAlien/ZipXtract#11]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, XLM, FTM, EPIC, ADA, XMR addresses available for donations (addresses have to be copyable).

Following an example from other developers.

![1000092943](https://github.com/cypherstack/stack_wallet/assets/113377431/44b05c36-ec6d-42db-b055-69272ccd4c63)

**Comment by WirelessAlien** [comment]
![-210230_temp](https://github.com/WirelessAlien/ZipXtract/assets/121420261/09ab8801-950d-4512-a1bd-4b56d2d6e388)
Added
