### ISSUE TITLE
[FEATURE] Localization

### ISSUE THREAD

**Issue by Cwpute** [WirelessAlien/ZipXtract#18]
**Is your feature request related to a problem? Please describe.**
Some users don't speak english and might need the app localized in their language.

**Describe the solution you'd like**
Provide a way for contributors to add localization for their own language. There are efficient tools out there like Weblate (opensource) or Crowdin.

**Describe alternatives you've considered**
Since this app does not feature a lot of text, it might be possible to get rid of any localized text and use symbols and icons instead. It shouldn't be too hard i think!

**Comment by WirelessAlien** [comment]
Provide a way for contributors to add localization for their own language. There are efficient tools out there like Weblate (opensource) or Crowdin.
> 
I requested for review to Weblate for hosting (it has not been approved yet). After approval I will let you know (here) then you can translate the strings and it will be added to the app.
> Since this app does not feature a lot of text, it might be possible to get rid of any localized text and use symbols and icons instead. It shouldn't be too hard i think!
> 
It can be done, but everything cannot be removed (like the extraction complete toast (or any other alert text)). For those text, we have to translate. So a method for localisation will be added.

**Comment by WirelessAlien** [comment]
@Cwpute you can translate the strings now-

https://hosted.weblate.org/projects/zipxtract/translate/

**Comment by Cwpute** [comment]
Done for french 👍 closing this as this has essentially been resolved now.

**Comment by Cwpute** [comment]
I think some apps use community translations for storage description and update logs ar well, not sure how they do it though.

**Comment by Cwpute** [comment]
Also realized that some parts of the app were not up for translation:
* options available in drop-down menus in the compression settings
* The Save button in that same menu
* information given by the question mark button near the Create Zip button
* Several toast menu texts

**Comment by WirelessAlien** [comment]
> Also realized that some parts of the app were not up for translation:
> 
> * options available in drop-down menus in the compression settings
> * The Save button in that same menu
> * information given by the question mark button near the Create Zip button
> * Several toast menu texts

Added to weblate.

**Comment by Cwpute** [comment]
Fantastic, all translated again :)

**Comment by essys** [comment]
Complete German translation added to Weblate.
