### ISSUE TITLE
[BUG] Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [WirelessAlien/ZipXtract#19]
**Describe the bug**
https://hosted.weblate.org/projects/zipxtract/#information says GPLv3-only,
whereas
https://github.com/search?q=repo%3AWirelessAlien%2FZipXtract%20any%20later&type=code
says GPLv3-or-later

**Additional context**

Can be changed to GPLv3-or-later in
https://hosted.weblate.org/settings/zipxtract/translate/
https://hosted.weblate.org/settings/zipxtract/glossary/

**Comment by WirelessAlien** [comment]
> **Describe the bug**
> https://hosted.weblate.org/projects/zipxtract/#information says GPLv3-only,
> whereas
> https://github.com/search?q=repo%3AWirelessAlien%2FZipXtract%20any%20later&type=code
> says GPLv3-or-later
> 
> **Additional context**
> 
> Can be changed to GPLv3-or-later in
> https://hosted.weblate.org/settings/zipxtract/translate/
> https://hosted.weblate.org/settings/zipxtract/glossary/

Done.

**Comment by comradekingu** [comment]
@WirelessAlien 
Now it is **L**GPL-3.0-or-later. and **L**GPL-**2.1**-or-later

**Comment by WirelessAlien** [comment]
> @WirelessAlien 
> Now it is **L**GPL-3.0-or-later. and **L**GPL-**2.1**-or-later

Ooh sorry. Now fixed.

**Comment by comradekingu** [comment]
Top stuff :)
