### ISSUE TITLE
[FEATURE] Support multi-volume archives

### ISSUE THREAD

**Issue by novellus** [WirelessAlien/ZipXtract#24]
**Is your feature request related to a problem? Please describe.**
The app does not appear to support multi-file archives.
I have tried the following naming schemes
* archive.part1.rar, archive.part2.rar, etc
* archive.rar, archive.r00, archive.r01, etc

I have tried using the first part of the archive as input, and I have tried using another part as input individually, but none of these are successful.

**Describe the solution you'd like**
I would like the program to support extraction of multipart archives. Supporting one or more of the common file naming conventions would be sufficient.
I propose one of the following UI designs:
* When I select the first part of an archive and hit extract, the program could automatically detect the other archive parts next to the input file
* Use a multi-file picker to select all the archive parts as input files in one go

**Additional context**
Currently, the program only extracts the first part of the archive, which results in an incomplete/corrupted output.

**Comment by WirelessAlien** [comment]
> **Is your feature request related to a problem? Please describe.** The app does not appear to support multi-file archives. I have tried the following naming schemes
> 
> * archive.part1.rar, archive.part2.rar, etc
> * archive.rar, archive.r00, archive.r01, etc
> 
> I have tried using the first part of the archive as input, and I have tried using another part as input individually, but none of these are successful.
> 
> **Describe the solution you'd like** I would like the program to support extraction of multipart archives. Supporting one or more of the common file naming conventions would be sufficient. I propose one of the following UI designs:
> 
> * When I select the first part of an archive and hit extract, the program could automatically detect the other archive parts next to the input file
> * Use a multi-file picker to select all the archive parts as input files in one go
> 
> **Additional context** Currently, the program only extracts the first part of the archive, which results in an incomplete/corrupted output.

I am working on it, will be added within a few days.
