### ISSUE TITLE
[BUG] App is not responding during ~65mb / ~7k files tar file extraction

### ISSUE THREAD

**Issue by EleanorRigby76** [WirelessAlien/ZipXtract#27]
**Describe the bug**
When extracting NumPy's tar archive from pypi.org (~65mb archive with ~7k files) I encountered the app constantly erroring with Android's not responding pop-up. The extraction succeeded however the app's UI was unresponsive during extraction thus Android decided to constantly prompt me to either kill the app or wait, choosing wait allowed the extraction to continue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to extract a tar archive with a large amount of small files.
2. Witness Android panic due to the app's UI not being responsive.
3. Sit through countless app is not responding pop-ups having to click wait on every single one.

**Expected behaviour**
The app's UI should be responsive, or at least not trigger Android's built-in app not responding prompt.

**Screenshots**
![IMG_20240211_124649](https://github.com/WirelessAlien/ZipXtract/assets/154634243/f01c593d-de3a-4a18-bbeb-4ed02314bc3d)
![IMG_20240211_125403](https://github.com/WirelessAlien/ZipXtract/assets/154634243/a732cbd5-c1b6-4bcc-b008-68182c65d459)
![IMG_20240211_125344](https://github.com/WirelessAlien/ZipXtract/assets/154634243/b8da8cd6-1c24-496b-9bf5-5fbde2db65ee)

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - App version 4.3 from F-Droid
 - Android 13 / LineageOS 20 - LineageOS 20-20231229-NIGHTLY-panther

**Additional context**
From my limited understanding of Android app development this shouldn't happen if the extraction function is called asynchronously so that the UI is able to update even while the extraction is running. [Kotlin docs on asynchronous programming are here.](https://kotlinlang.org/docs/async-programming.html)

**Comment by WirelessAlien** [comment]
I released a new version (just updated the code to do the job in background), let me know it is fixed or not. I will not close the issue now.
