### ISSUE TITLE
Add support  rar

### ISSUE THREAD

**Issue by Stu75e** [WirelessAlien/ZipXtract#5]

**Comment by Spp595** [comment]
I would really like to have support! I have to use another application to create rar archives

**Comment by WirelessAlien** [comment]
> I would really like to have support! I have to use another application to create rar archives

It is planned but it has some implementation problem. wait for sometime, it will be added.

**Comment by WirelessAlien** [comment]
> 

RAR extraction added.

**Comment by WirelessAlien** [comment]
> I would really like to have support! I have to use another application to create rar archives

I added the extraction of RAR but creation of rar is not possible.

**Comment by essys** [comment]
> > I would really like to have support! I have to use another application to create rar archives
> 
> I added the extraction of RAR but creation of rar is not possible.

Is that because it is a proprietary format?
Extraction of rar files is already a major feature many thanks for adding this, that's great.

**Comment by WirelessAlien** [comment]
> > > I would really like to have support! I have to use another application to create rar archives
> > 
> > 
> > I added the extraction of RAR but creation of rar is not possible.
> 
> Is that because it is a proprietary format? 
>
Yes. Have to take written permission for licence with fees to add rar creation.
>Extraction of rar files is already a major feature many thanks for adding this, that's great.
>
Welcome.
