### ISSUE TITLE
Support "Open with" operations

### ISSUE THREAD

**Issue by Cwpute** [WirelessAlien/ZipXtract#6]
ZipXtract currently doesn't support all "Open with" operations, which would be very convenient for interacting with other apps.

My problem is that i'd like to use ZipXtract in combination with [LittleFileExplorer](https://github.com/martinmimigames/little-file-explorer/), and currently this isn't possible and requires to use the pre-installed file browser from vithin ZipXtract.

This issue was raised by a comment on the LittleFileExplorer issue tracker: https://github.com/martinmimigames/little-file-explorer/issues/61
May be related to #4

**Comment by WirelessAlien** [comment]
Oh.  I forgot, I was busy with my exams.  I will add this within 2 days 👍

**Comment by Cwpute** [comment]
wow that was super fast. thanks!
